name: Publish Rules on Agent Release

on:
  push:
    tags:
      - agent-v*

env:
  AWS_PAGER: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARCHODEX_RULES_AWS_ROLE_ARN }}
          aws-region: us-west-2
          mask-aws-account-id: true
          role-chaining: env.ACT == 'true'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate versions.json
        run: |
          git fetch --tags
          git tag --list 'agent-v*' | sort -rV | jq -R -s --indent 2 'split("\n") | map(select(length>0)) | {versions: .}' > versions.json

      - name: Generate rules.json
        run: |-
          ls rules/*.yaml | \
            sed 's|rules/||; s|\.yaml$||' | \
            jq -R -s '{ rules: (split("\n") | map(select(length>0))) }' > rules/rules.json

      - name: Sync rules to S3
        run: |-
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          aws s3 sync --exclude '*' --include '*.yaml' --delete --content-type application/yaml --content-disposition inline rules/ s3://archodex-rules-assets-${ACCOUNT_ID}/${{ github.ref_name }}/
          aws s3 sync --exclude '*' --include '*.json' --delete --content-type application/json --content-disposition inline rules/ s3://archodex-rules-assets-${ACCOUNT_ID}/${{ github.ref_name }}/
          aws s3 cp versions.json s3://archodex-rules-assets-${ACCOUNT_ID}/
