name: Deploy Infrastructure and Publish Dev Rules

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_PAGER: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ArchodexRulesGithubActionsRole
          mask-aws-account-id: true

      - uses: actions/checkout@v4

      - name: Deploy Infrastructure
        run: |
          aws cloudformation deploy \
            --stack-name archodex-rules \
            --template-file template.yaml \
            --capabilities CAPABILITY_NAMED_IAM \
            --disable-rollback

      - name: Generate rules.json
        run: |-
          ls rules/*.yaml | \
            sed 's|rules/||; s|\.yaml$||' | \
            jq -R -s '{ rules: (split("\n") | map(select(length>0))) }' > rules/rules.json

      - name: Sync rules to S3
        run: |-
          aws s3 sync --exclude '*' --include '*.yaml' --delete --content-type application/yaml --content-disposition inline rules/ s3://archodex-rules-assets-${{ secrets.AWS_ACCOUNT_ID }}/dev/
          aws s3 sync --exclude '*' --include '*.json' --delete --content-type application/json --content-disposition inline rules/ s3://archodex-rules-assets-${{ secrets.AWS_ACCOUNT_ID }}/dev/